toggle change
RedstoneTools/redstonetools pull request #119
Opened 2023-03-11 19:43 UTC by Ninty9

kept the onEnable and onDisable functions for eventual feedback functionality in the future

2023-03-11 22:03 UTC, Matthias1590 commented
might be nice to just send feedback in the run method so features don't have to do that themselves

2023-03-11 22:03 UTC, Matthias1590 requested changes

2023-03-11 22:03 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/toggleable/ToggleableFeature.java
> +    private int run(CommandContext<ServerCommandSource> context) throws CommandSyntaxException {
might be nice to rename this to toggle

2023-03-12 12:28 UTC, Ninty9 commented
> might be nice to just send feedback in the run method so features don't have to do that themselves

that's definitely doable, but shouldn't we wait until we have the feedback util for that?

2023-03-12 12:37 UTC, Matthias1590 commented
> > might be nice to just send feedback in the run method so features don't have to do that themselves
> 
> that's definitely doable, but shouldn't we wait until we have the feedback util for that?

Might be easier to just do it now so we can refactor it later and not risk forgetting about it

2023-03-12 15:20 UTC, Ninty9 commented
That should be everything

2023-03-12 15:42 UTC, Matthias1590 approved these changes

2023-03-12 15:43 UTC, merged