Removed //update gamerule and added optional argument for updating last edit
RedstoneTools/redstonetools pull request #121
Opened 2023-03-11 20:01 UTC by MiranCZ

resolves #116

2023-03-13 20:54 UTC, Matthias1590 requested changes

2023-03-13 20:54 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +    public static final Argument<Boolean> updateLastEdit = Argument
Could you register a separate command, `//update last`, instead of this arg?

2023-03-13 20:54 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/mixin/LocalSessionMixin.java
> +        UpdateFeature.lastEdit = editSession;
Might be nice to invert this, have the last edit be a static variable of LocalSessionMixin instead of UpdateFeature

2023-03-13 20:54 UTC, Matthias1590 commented
Also please use the new feedback system instead of sending messages directly to the source

2023-03-13 21:00 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +    public static final Argument<Boolean> updateLastEdit = Argument
Yeah, sounds good

2023-03-14 09:20 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +    public static final Argument<Boolean> updateLastEdit = Argument
Should be like `//update [last/selected]` with default being `selected`?

2023-03-14 09:47 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/mixin/LocalSessionMixin.java
> +        UpdateFeature.lastEdit = editSession;
I sadly cant do that, because `public static` members are not allowed in mixin classes

2023-03-14 10:07 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/mixin/LocalSessionMixin.java
> +        UpdateFeature.lastEdit = editSession;
In that case, maybe use WorldEditUtils

2023-03-14 10:09 UTC, Matthias1590 requested changes

2023-03-14 10:09 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
Might be better if you call the super implementation and additionally register the //update last command

2023-03-14 10:09 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +public class UpdateFeature extends AbstractFeature {
If you call super in the registerCommands method you can extend CommandFeature

2023-03-14 10:11 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +public class UpdateFeature extends AbstractFeature {
but then I need `execute(ServerCommandSource source) method`

2023-03-14 10:12 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
using literal.then

2023-03-14 10:12 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
But super.registerCommands doesnt return the ArgumentBuilder

2023-03-14 10:13 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
you dont need the argument builder, if you call dispatcher.register twice it'll work just fine

2023-03-14 10:14 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
wont that overwrite the original command node

2023-03-14 10:14 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
pretty sure it wont

2023-03-14 10:15 UTC, orbyfied commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").executes(this::executeSelected).then(literal("last").executes(this::executeLast)));
I dont see a way it wouldnt but you could try. Still think constructMainCommand would be useful though

2023-03-14 10:15 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +            return executeWithArg(serverCommandSourceCommandContext.getSource(),true);
this could just call updateLastEdit(source) directly as thats the only thing executeWithArg does

2023-03-14 10:15 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        return executeWithArg(source,false);
The execute selection code could be moved here

2023-03-14 10:17 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +            return executeWithArg(serverCommandSourceCommandContext.getSource(),true);
oh, right

2023-03-14 10:20 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").then(literal("last").executes(this::executeLast)));
this::executeLast could be replaced with updateLastEdit, in the body of the updateLastEdit method you can get the source

2023-03-14 10:20 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +    private int executeLast(CommandContext<ServerCommandSource> serverCommandSourceCommandContext) {
this method can be deleted

2023-03-14 10:21 UTC, orbyfied commented
Shouldn't there be a `super.registerCommands` call at the start of `registerCommands`

2023-03-14 10:22 UTC, MiranCZ commented
> Shouldn't there be a `super.registerCommands` call at the start of `registerCommands`

yeah, there definitelly should

2023-03-14 10:25 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/update/UpdateFeature.java
> +        dispatcher.register(literal("/update").then(literal("last").executes(this::executeLast)));
maaan, what am I doing :p

2023-03-14 10:27 UTC, Matthias1590 submitted a review, later dismissed

2023-03-14 10:28 UTC, Matthias1590 commented
Can you confirm whether the registering of the commands works in-game as expected?

2023-03-14 10:29 UTC, MiranCZ commented
yeah, I tested it. it does

2023-03-14 10:29 UTC, Matthias1590 commented
> yeah, I tested it. it does

Awesome, thanks. I'll merge once conflicts are resolved

2023-03-14 10:35 UTC, Matthias1590 commented
> I think it should be resolved

Doesn't look like it'd build

2023-03-14 10:43 UTC, Matthias1590 commented
I can try to resolve the conflicts later if you want

2023-03-14 10:48 UTC, MiranCZ commented
I am on it, this will take some time

2023-03-14 12:51 UTC, merged