Adds update popup
RedstoneTools/redstonetools pull request #153
Opened 2023-04-27 19:12 UTC by RUGMJ

Adds a popup after the title screen indicating to the user if theres an update available, it knows this from the github releases api, currently this system wont work for betas or if we add support to more than 1 mc version at a time

2023-04-27 19:16 UTC, RUGMJ commented
Only just realised my auto formatter changed some things. if this is an issue I can revert those changes

2023-04-30 07:53 UTC, Matthias1590 requested changes

2023-04-30 07:53 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +            Request request = new Request.Builder()
I think we might want to move the request stuff into a different thread so it doesn't freeze the ui, make sure to test without an internet connection as well

2023-04-30 07:53 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +        } catch (JsonSyntaxException e) {
These 2 catch clauses can be ored together `catch (JsonSyntaxException | IOException e)`

2023-04-30 07:53 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/gui/UpdatePopupScreen.java
> +            RedstoneToolsClient.LOGGER.info("Ignored Update");
Don't think this needs an info log or a log at all

2023-04-30 07:56 UTC, RUGMJ commented on src/main/java/tools/redstone/redstonetools/gui/UpdatePopupScreen.java
> +            RedstoneToolsClient.LOGGER.info("Ignored Update");
My bad that was leftover from debugging

2023-04-30 07:57 UTC, RUGMJ commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +            Request request = new Request.Builder()
That's what the trycatch blocks are for but I haven't actually tested that

2023-04-30 07:58 UTC, RUGMJ commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +            Request request = new Request.Builder()
The ui should freeze, it would be strange for the pop up to show before the title screen sometimes and a second after at others

2023-04-30 08:00 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +            Request request = new Request.Builder()
Fair, I guess it's fine if we have a small timeout on the request, maybe like .25 seconds

2023-04-30 08:03 UTC, RUGMJ commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +            Request request = new Request.Builder()
Sounds good

2023-04-30 14:52 UTC, Matthias1590 commented on src/main/java/tools/redstone/redstonetools/mixin/UpdatePopupMixin.java
> +    private static long timeout = 250;
Could be a constant but this works

2023-04-30 14:52 UTC, Matthias1590 approved these changes

2023-04-30 14:52 UTC, merged