Dustplacer Feature
RedstoneTools/redstonetools pull request #82
Opened 2023-02-23 10:56 UTC by Ninty9

Basic functionality for the feature is done

2023-02-23 19:17 UTC, MiranCZ commented on src/main/java/com/domain/redstonetools/features/commands/DustPlacerFeature.java
> +        if(blockList.isEmpty()) {
maybe add a `static{` statement to add all those values into list

2023-02-23 21:55 UTC, Ninty9 commented on src/main/java/com/domain/redstonetools/features/commands/DustPlacerFeature.java
> +        if(blockList.isEmpty()) {
Good idea, added. (also cleaned up a method that was lying around for some reason, don't know why i overlooked that.)

2023-02-24 08:13 UTC, Matthias1590 requested changes
The list of blocks should be stored in a settings file, the toggling of the feature should be done using 2 commands: /autodust enable and /autodust disable (override the registerCommands method to register them)

2023-03-06 19:19 UTC, Matthias1590 commented
any updates on this?

2023-03-08 09:16 UTC, orbyfied commented
> The list of blocks should be stored in a settings file (use dependency injection to inject something like a config provider or config reader into the autodust feature), the toggling of the feature should be done using 2 commands: /autodust enable and /autodust disable (override the registerCommands method to register them)

I think we should first get a configuration system working.

2023-03-08 10:40 UTC, Matthias1590 commented
> > The list of blocks should be stored in a settings file (use dependency injection to inject something like a config provider or config reader into the autodust feature), the toggling of the feature should be done using 2 commands: /autodust enable and /autodust disable (override the registerCommands method to register them)
> 
> I think we should first get a configuration system working.

that would be the configuration system

2023-03-08 20:50 UTC, closed without merging

2023-03-08 20:54 UTC, MiranCZ commented
Why was this closed?