Add rstack
RedstoneTools/redstonetools pull request #99
Opened 2023-03-07 17:19 UTC by DiamondTaco

i use a lot of switch cases in the implementation, so im open to another solution if there is one.

2023-03-07 17:54 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +                case UP, DOWN -> throw new CommandException(Text.of("Can't determine direction"));
if you are facing straight up or down i can't figure out what direction to spawn the stack in, but for back i can just flip direction. returning the same direction was a bug tho

2023-03-07 17:55 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +                case UP, DOWN -> throw new CommandException(Text.of("Can't determine direction"));
fixed

2023-03-13 06:48 UTC, Matthias1590 requested changes

2023-03-13 06:52 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +    private static final Set<String> DIRS = Set.of(
We can't use a we class bc they use a parser to parse directions, not just a set of strings. I think its better to leave this as a set of strings, this is just used to accept directional input and WE already has a direction enum for dealing with actual directions

2023-03-13 06:56 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +    private static final Set<String> DIRS = Set.of(
> We can't use a we class bc they use a parser to parse directions, not just a set of strings. I think its better to leave this as a set of strings, this is just used to accept directional input and WE already has a direction enum for dealing with actual directions

An enum is less error prone and would remove the need for half of the code in this feature

2023-03-13 06:58 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +    private static final Set<String> DIRS = Set.of(
> > We can't use a we class bc they use a parser to parse directions, not just a set of strings. I think its better to leave this as a set of strings, this is just used to accept directional input and WE already has a direction enum for dealing with actual directions
> 
> An enum is less error prone and would remove the need for half of the code in this feature

not really, most of the matching is parsing the directions directly. unless you want to remove features like "//rstack 5 up" you have to live with with the boilerplate (AFAIK)

2023-03-13 07:00 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +    private static final Set<String> DIRS = Set.of(
Enums can get rid of most boilerplate in this case

2023-03-13 07:01 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionArgumentType.java
> +    private static final Set<String> DIRS = Set.of(
well i don't know how they would, can you provide an example on how they would match relative directions like left, back, etc?

2023-03-14 20:40 UTC, Matthias1590 requested changes

2023-03-14 20:40 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionSerializer.java
> +    public static DirectionSerializer directionArgument() {
Could be renamed to direction

2023-03-14 20:41 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionSerializer.java
> +    public static DirectionSerializer directionArgument() {
which one? DirectionSerializer or directionArgument()

2023-03-14 20:42 UTC, Matthias1590 commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionSerializer.java
> +    public static DirectionSerializer directionArgument() {
directionArgument

2023-03-14 20:42 UTC, DiamondTaco commented on src/main/java/com/domain/redstonetools/features/arguments/DirectionSerializer.java
> +    public static DirectionSerializer directionArgument() {
done

2023-03-14 20:43 UTC, merged